# Generated by Django 4.2 on 2024-07-31 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0003_product_archive'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='archive',
            new_name='archived',
        ),
    ]
